[package]
name = "semen-sinapis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "entity", "layer", "macros", "migration", "utils"]

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = { version = "0", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros", "with-time", "with-json", "postgres-array"] }
tokio = { version = "1", features = ["full"] }
tower = "0"
tonic = { version = "0.8", features = ["transport", "prost", "codegen"] }
dotenv = "0"
dapr = "0"
prost = "0.11"
prost-types = "0.11"
serde_json = "1"
time = "0"
async-recursion = "1"

[build-dependencies]
tonic-build = "0.8"
