[package]
name = "semen-sinapis"
version = "0.1.0"
edition = "2021"

[profile.dev]
build-override.debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = [
    "entity",
    "layer",
    "macros",
    "migration",
    "utils",
    "volo-gen",
    "person-center",
    "aggregation-gateway",
    "frontend-base-service",
    "idgen",
    "pool",
]

[[bin]]
name = "person-center"
path = "person-center/src/main.rs"

[[bin]]
name = "aggregation-gateway"
path = "aggregation-gateway/src/main.rs"

[[bin]]
name = "frontend-base-service"
path = "frontend-base-service/src/main.rs"

[workspace.dependencies]
dapr = "0"
volo = "0"
volo-grpc = "0"
volo-build = "0"
anyhow = "1"
async-trait = "0"
futures = "0"
pilota = "0"
mime = "0"
serde = "1"
serde_yaml = "0.9"
serde_json = "1"
tracing = "0"
prost-types = "0"
chrono = "0"
console_error_panic_hook = "0"
tower-service = "0"
tower-layer = "0"
tower = "0.5"
tower-http = "0.6"
wasm-bindgen = "0.2.93"
thiserror = "1"
http = "1"
jsonwebtoken = "9"
bytes = "1"
http-body = "1"
forwarded-header-value = "0.1"
apache_age = "0.6"
tokio-postgres = "0.7"
dotenv = "0.15"
sonic-rs = "0.3"
lazy_static = "1"
tracing-subscriber = "0.3"
axum = "0"
axum-macros = "0"
leptos = "0.7.0-rc0"
leptos_axum = "0.7.0-rc0"
leptos_meta = "0.7.0-rc0"
leptos_router = "0.7.0-rc0"
leptos-use = { git = "https://github.com/Synphonyte/leptos-use.git", branch = "leptos-0.7" }
utoipa = "5"
utoipa-swagger-ui = "8"
sea-orm = "1"
tokio = "1"
argon2 = "0"
nacos-sdk = "0"
uuid = "1"
cookie = "0.18"
redis-om = "0.1"
bb8 = "0.8"
pin-project = "1"
